#!/usr/bin/env python3
"""Execute a plan generated by plan.py.

Honors --dry-run. Probes writability before each operation and surfaces SMB
ACL failures clearly. Logs every action.

Usage:
    python3 execute.py <plan.json> [--dry-run] [--log execute.log]
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
from datetime import datetime


def writable(path: str) -> bool:
    if not os.path.isdir(path):
        return False
    test = os.path.join(path, f".wtest-{os.getpid()}")
    try:
        with open(test, "w") as f:
            f.write("t")
        os.unlink(test)
        return True
    except (OSError, PermissionError):
        return False


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("plan", help="plan.json path")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--log", default=None, help="log file (default: execute-<ts>.log)")
    p.add_argument("--fuzzy-fallback", action="store_true",
                   help="When a target folder is missing, fuzzy-match against existing dirs")
    args = p.parse_args()

    with open(args.plan, encoding="utf-8") as f:
        plan = json.load(f)

    root = plan["root"]
    if not os.path.isdir(root):
        raise SystemExit(f"Plan root not a directory: {root}")
    os.chdir(root)

    log_path = args.log or f"execute-{datetime.now().strftime('%Y%m%d-%H%M%S')}.log"
    log_path = os.path.join("/tmp", log_path) if not os.path.isabs(log_path) else log_path
    logf = open(log_path, "w", encoding="utf-8")

    def log(msg: str):
        print(msg)
        logf.write(msg + "\n")
        logf.flush()

    log(f"Plan: {args.plan}")
    log(f"Root: {root}")
    log(f"Mode: {'DRY RUN' if args.dry_run else 'LIVE'}")
    log(f"Log:  {log_path}")
    log("")

    succeeded = 0
    failed = 0
    skipped = 0

    # In dry-run mode, track paths the plan would create so subsequent move
    # ops don't false-positive on "target dir missing". This makes dry-run
    # an honest preview of what live would do.
    simulated_dirs = set()

    for op in plan["operations"]:
        kind = op["op"]
        cat = op.get("category", "?")

        if kind == "mkdir_if_absent":
            path = op["path"]
            if os.path.exists(path) or path in simulated_dirs:
                continue
            if args.dry_run:
                log(f"  [DRY][{cat}] mkdir '{path}'")
                simulated_dirs.add(path)
                succeeded += 1
                continue
            try:
                os.makedirs(path)
                log(f"  [{cat}] mkdir '{path}'")
                succeeded += 1
            except OSError as e:
                log(f"  [{cat}] ERR mkdir '{path}': {e}")
                failed += 1

        elif kind == "rename_dir":
            src = op["src"]
            dst = op["dst"]
            if not os.path.exists(src):
                log(f"  [{cat}] MISSING src: {src}")
                skipped += 1
                continue
            if os.path.exists(dst):
                log(f"  [{cat}] SKIP exists: {dst} (src={src})")
                skipped += 1
                continue
            if args.dry_run:
                log(f"  [DRY][{cat}] mv dir '{src}' → '{dst}'")
                simulated_dirs.add(dst)
                succeeded += 1
                continue
            try:
                os.rename(src, dst)
                log(f"  [{cat}] mv dir '{src}' → '{dst}'")
                succeeded += 1
            except OSError as e:
                log(f"  [{cat}] ERR mv '{src}' → '{dst}': {e}")
                failed += 1

        elif kind == "move":
            src = op["src"]
            dst = op["dst"]
            if not os.path.exists(src):
                log(f"  [{cat}] MISSING src: {src}")
                skipped += 1
                continue
            if os.path.exists(dst):
                log(f"  [{cat}] SKIP exists: {dst}")
                skipped += 1
                continue
            target_dir = os.path.dirname(dst)
            # In dry-run, accept simulated dirs from earlier ops in this plan.
            if target_dir and not os.path.exists(target_dir) and target_dir not in simulated_dirs:
                # Maybe Cat B renamed it. Fall back to fuzzy lookup if enabled.
                if args.fuzzy_fallback:
                    ty = op.get("title_year")
                    if ty and (os.path.exists(ty) or ty in simulated_dirs):
                        dst = os.path.join(ty, os.path.basename(dst))
                        target_dir = ty
                    else:
                        log(f"  [{cat}] ERR target dir missing: {target_dir}")
                        failed += 1
                        continue
                else:
                    log(f"  [{cat}] ERR target dir missing: {target_dir}")
                    failed += 1
                    continue
            if args.dry_run:
                log(f"  [DRY][{cat}] mv '{src}' → '{dst}'")
                succeeded += 1
                continue
            try:
                os.rename(src, dst)
                log(f"  [{cat}] mv '{src}' → '{dst}'")
                succeeded += 1
            except OSError as e:
                # SMB sometimes refuses cross-directory directory moves.
                # If src is a directory and dst is in a different parent, retry with cp+rm.
                if isinstance(e, PermissionError) or e.errno == 13:
                    if os.path.isdir(src):
                        log(f"  [{cat}] mv failed (dir cross-folder); will need cp+rm fallback: '{src}' → '{dst}': {e}")
                    else:
                        log(f"  [{cat}] ERR (permission) mv '{src}' → '{dst}': {e}")
                else:
                    log(f"  [{cat}] ERR mv '{src}' → '{dst}': {e}")
                failed += 1

        else:
            log(f"  Unknown op: {kind}")
            failed += 1

    log("")
    log(f"Done. succeeded={succeeded} failed={failed} skipped={skipped}")
    log(f"Log file: {log_path}")
    logf.close()
    if failed > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
